/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Logic_UI.Departement;
import Logic_UI.Faculte;
import Logic_UI.db_Mysql;
import Manager_UI.Manager_Dep_CombBox;
import Manager_UI.Manager_Departement_UI;
import Manager_UI.Manager_Ev_MenuDep;
import Manager_UI.Manager_Tab_Dep_UI;
import Model_Table.Model_Departement;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author utilisateur
 */
public class DepartementUI extends javax.swing.JFrame {

    /**
     * Creates new form DepartementUI
     */
    static Faculte choix_fac=null;
    

   

    public JButton getBt_dep_enre() {
        return bt_dep_enre;
    }

    public void setBt_dep_enre(JButton bt_dep_enre) {
        this.bt_dep_enre = bt_dep_enre;
    }

    public JButton getjButton1() {
        return bt_mod_dep;
    }

    public void setjButton1(JButton jButton1) {
        this.bt_mod_dep = jButton1;
    }
   
    public static Departement depID=null;
    public DepartementUI() {
       // depID.get
        initComponents();
        this.setLocationRelativeTo(null);
        Faculte.Loading_Faculty(fac);
        bt_dep_enre.addActionListener(new Manager_Departement_UI(this));
        bt_mod_dep.setEnabled(false);
        tab_Dep.setModel(new Model_Departement(Departement.charger_Depart_Tableau()));
        tab_Dep.getSelectionModel().addListSelectionListener(new Manager_Tab_Dep_UI(this));
        inscrMen.addActionListener(new Manager_Ev_MenuDep(this));
        facMen.addActionListener(new Manager_Ev_MenuDep(this));
        clasMen.addActionListener(new Manager_Ev_MenuDep(this));
        depClMen.addActionListener(new Manager_Ev_MenuDep(this));
        etudMen.addActionListener(new Manager_Ev_MenuDep(this));
    
    }

    public JButton getBt_mod_dep() {
        return bt_mod_dep;
    }

    public void setBt_mod_dep(JButton bt_mod_dep) {
        this.bt_mod_dep = bt_mod_dep;
    }

    public static Faculte getChoix_fac() {
        return choix_fac;
    }

    public JTextField getNom_dep() {
        return nom_dep;
    }

    public JComboBox<String> getFac() {
        return fac;
    }
 /*  Manager_Departement_UI creer_Objet(){
       if(choix_fac!=null)
     return new Manager_Departement_UI(choix_fac,this.nom_dep.getText());
       return null;
   }
    */
    
    public static void setChoix_fac(Faculte choix_fac) {
        choix_fac = choix_fac;
    }

    public JTable getTab_Dep() {
        return tab_Dep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fac = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nom_dep = new javax.swing.JTextField();
        bt_dep_enre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Dep = new javax.swing.JTable();
        bt_mod_dep = new javax.swing.JButton();
        recudep_ID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        inscrMen = new javax.swing.JMenuItem();
        facMen = new javax.swing.JMenuItem();
        clasMen = new javax.swing.JMenuItem();
        depClMen = new javax.swing.JMenuItem();
        etudMen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setText("Page pour gérer les Départements de BD");

        jLabel2.setText("Nom de la Faculté");

        fac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Nom du département");

        bt_dep_enre.setText("Enregistrer Département");
        bt_dep_enre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dep_enreActionPerformed(evt);
            }
        });

        tab_Dep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_Dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_DepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_Dep);

        bt_mod_dep.setText("Modifier Département");
        bt_mod_dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mod_depMouseClicked(evt);
            }
        });

        recudep_ID.setFont(new java.awt.Font("Tahoma", 0, 2)); // NOI18N
        recudep_ID.setForeground(new java.awt.Color(240, 240, 240));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Navigation_Menu");
        jMenu1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N

        inscrMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        inscrMen.setText("Inscription");
        inscrMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrMenActionPerformed(evt);
            }
        });
        jMenu1.add(inscrMen);

        facMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        facMen.setText("Faculté");
        jMenu1.add(facMen);

        clasMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        clasMen.setText("Classe");
        jMenu1.add(clasMen);

        depClMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        depClMen.setText("Département_Classe");
        jMenu1.add(depClMen);

        etudMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        etudMen.setText("Etudiant");
        jMenu1.add(etudMen);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(recudep_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fac, 0, 174, Short.MAX_VALUE)
                    .addComponent(nom_dep))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(bt_dep_enre)
                        .addGap(18, 18, 18)
                        .addComponent(bt_mod_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(recudep_ID))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_dep_enre)
                    .addComponent(bt_mod_dep))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_dep_enreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dep_enreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_dep_enreActionPerformed

    private void bt_mod_depMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mod_depMouseClicked
        // TODO add your handling code here:
        if(fac.getSelectedItem().equals("select Faculte")||nom_dep.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Pas d'informaton necessaire!!!");
        }
        else{
            
            String Query1="Update departement set nom='"+nom_dep.getText()+"'"+"where departID="+recudep_ID.getText();
            db_Mysql.updateBD(Query1);
            /*bt_mod_dep.setEnabled(false);
            bt_dep_enre.setEnabled(true);*/
            DepartementUI patp=new DepartementUI();
        patp.setVisible(true);
        patp.pack();
        patp.setLocationRelativeTo(null);
        patp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
            JOptionPane.showMessageDialog(this,"Modification reussi!!!");
        }
    }//GEN-LAST:event_bt_mod_depMouseClicked

    private void tab_DepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_DepMouseClicked
        // TODO add your handling code here:
       Model_Departement model=(Model_Departement)tab_Dep.getModel();
        int Myindex = tab_Dep.getSelectedRow();
        fac.setEditable(true);
        fac.setSelectedItem(model.getValueAt(Myindex,1).toString());
        recudep_ID.setText(model.getValueAt(Myindex,0).toString());
        /*fac.setSelectedItem(model.getValueAt(Myindex,1).toString());
        nom_dep.setText(model.getValueAt(Myindex,2).toString());*/
    }//GEN-LAST:event_tab_DepMouseClicked

    private void inscrMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscrMenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dep_enre;
    private javax.swing.JButton bt_mod_dep;
    private javax.swing.JMenuItem clasMen;
    private javax.swing.JMenuItem depClMen;
    private javax.swing.JMenuItem etudMen;
    private javax.swing.JComboBox fac;
    private javax.swing.JMenuItem facMen;
    private javax.swing.JMenuItem inscrMen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nom_dep;
    private javax.swing.JLabel recudep_ID;
    private javax.swing.JTable tab_Dep;
    // End of variables declaration//GEN-END:variables
}
