/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Logic_UI.db_Mysql;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class EtudianGesttUI extends javax.swing.JFrame {

    /**
     * Creates new form EtudiantUI
     */
    public EtudianGesttUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        AfficherTable();
        btn_Enregistrer.setEnabled(true);
        btn_Modifier.setEnabled(false);
        Donnée_Etud();
        Donnée_Faculte();
        Donnée_Departement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void Donnée_Etud(){
        
        try{
            
           Class.forName("com.mysql.jdbc.Driver");
	   Connection _con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ult_inscription", "root", "");
           Statement stm = _con.createStatement();
           ResultSet rs = stm.executeQuery("select concat(nom,' ',prenom) as etudiant from etudiant");
           
           while(rs.next()){
               String etudiant = rs.getString("etudiant");
               etud.addItem(etudiant);
           }
           _con.close();
            
        }
        catch(Exception e){
            
        }
    }
    
    public void Donnée_Faculte(){
        
        try{
            
           Class.forName("com.mysql.jdbc.Driver");
	   Connection _con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ult_inscription", "root", "");
           Statement stm = _con.createStatement();
           ResultSet rs = stm.executeQuery("select nom from faculte");
           
           while(rs.next()){
               String faculte = rs.getString("nom");
               fac.addItem(faculte);
           }
           _con.close();
            
        }
        catch(Exception e){
            
        }
    }
    
    public void Donnée_Departement(){
        
        try{
            
           Class.forName("com.mysql.jdbc.Driver");
	   Connection _con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ult_inscription", "root", "");
           Statement stm = _con.createStatement();
           ResultSet rs = stm.executeQuery("select nom from departement");
           
           while(rs.next()){
               String departement = rs.getString("nom");
               dep.addItem(departement);
           }
           _con.close();
            
        }
        catch(Exception e){
            
        }
    }
    
     ResultSet Rs=null;
public void AfficherTable(){
    
    /*Rs=db_Mysql.interrogerBD("select etud_InscrID,faculte,departement,classe,etudiant,anneeAc from etudiantinsc order by anneeAc");*/
    Rs=db_Mysql.interrogerBD("select * from etudiantinsc");
    etudInscTab.setModel(DbUtils.resultSetToTableModel(Rs));
}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Enregistrer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fac = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dep = new javax.swing.JComboBox<>();
        etud = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ac = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        clas = new javax.swing.JComboBox<>();
        btn_Modifier = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        etudInscTab = new javax.swing.JTable();
        recup_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Enregistrer.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btn_Enregistrer.setText("Enregistrer");
        btn_Enregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EnregistrerMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setText("Faculté");

        fac.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText("Département");

        dep.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        etud.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setText("Etudiant");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("Année Academique");

        ac.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        ac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023" }));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setText("Classe");

        clas.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        clas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bac1", "Bac2", "Bac3" }));

        btn_Modifier.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btn_Modifier.setText("Modifier");
        btn_Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModifierMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setText("Page gérant les inscription des étudiants");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        etudInscTab.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        etudInscTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        etudInscTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etudInscTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(etudInscTab);

        recup_id.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        recup_id.setForeground(new java.awt.Color(240, 240, 240));
        recup_id.setText("recup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(recup_id)
                                .addGap(8, 8, 8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ac, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                                .addComponent(clas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fac, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(etud, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(recup_id)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(etud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EnregistrerMouseClicked
        // TODO add your handling code here:
     etud.getSelectedItem();
     fac.getSelectedItem();
     dep.getSelectedItem();
     clas.getSelectedItem();
     ac.getSelectedItem();
        db_Mysql.updateBD("insert into etudiantinsc(etudiant,faculte,departement,classe,anneeAc)"
             + "values('"+etud.getSelectedItem()+"','"+fac.getSelectedItem()+"','"+dep.getSelectedItem()
            +"','"+clas.getSelectedItem()+"','"+ac.getSelectedItem()+"')");
        AfficherTable();
    }//GEN-LAST:event_btn_EnregistrerMouseClicked

    private void btn_ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModifierMouseClicked
        // TODO add your handling code here:
        String Query="Update etudiantinsc set etudiant='"+etud.getSelectedItem()+"'"+",faculte='"+fac.getSelectedItem()+"'"+",departement='"+dep.getSelectedItem()+"'"+",classe='"+clas.getSelectedItem()+"'"+",anneeAc='"+ac.getSelectedItem()+"'"+"where etud_InscrID="+recup_id.getText();
        db_Mysql.updateBD(Query);
        AfficherTable();
        btn_Enregistrer.setEnabled(true);
        btn_Modifier.setEnabled(false);
        JOptionPane.showMessageDialog(this,"Modification reussi!!!");
    }//GEN-LAST:event_btn_ModifierMouseClicked

    private void etudInscTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etudInscTabMouseClicked
        // TODO add your handling code here:
        btn_Enregistrer.setEnabled(false);
        btn_Modifier.setEnabled(true);
        DefaultTableModel model=(DefaultTableModel)etudInscTab.getModel();
        int Myindex = etudInscTab.getSelectedRow();
        etud.setEditable(true);
        etud.setSelectedItem(model.getValueAt(Myindex,1).toString());
        fac.setEditable(true);
        fac.setSelectedItem(model.getValueAt(Myindex,2).toString());
        dep.setEditable(true);
        dep.setSelectedItem(model.getValueAt(Myindex,3).toString());
        clas.setEditable(true);
        clas.setSelectedItem(model.getValueAt(Myindex,4).toString());
        ac.setEditable(true);
        ac.setSelectedItem(model.getValueAt(Myindex,5).toString());
        recup_id.setText(model.getValueAt(Myindex,0).toString());
    }//GEN-LAST:event_etudInscTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtudianGesttUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtudianGesttUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtudianGesttUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtudianGesttUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtudianGesttUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ac;
    private javax.swing.JButton btn_Enregistrer;
    private javax.swing.JButton btn_Modifier;
    private javax.swing.JComboBox<String> clas;
    private javax.swing.JComboBox<String> dep;
    private javax.swing.JComboBox<String> etud;
    private javax.swing.JTable etudInscTab;
    private javax.swing.JComboBox<String> fac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel recup_id;
    // End of variables declaration//GEN-END:variables
}
