/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Manager_UI.Manager_Ev_MenuFac;
import Manager_UI.Manager_Faculte_UI;
import javax.swing.JTextField;

/**
 *
 * @author utilisateur
 */
public class FaculteUI extends javax.swing.JFrame {

    /**
     * Creates new form FaculteUI
     */
    public FaculteUI() {
        
        initComponents();
        bt_enr.addActionListener(new Manager_Faculte_UI(this));
        this.setLocationRelativeTo(null);
        inscrMen.addActionListener(new Manager_Ev_MenuFac(this));
        depMen.addActionListener(new Manager_Ev_MenuFac(this));
        clasMen.addActionListener(new Manager_Ev_MenuFac(this));
        depClMen.addActionListener(new Manager_Ev_MenuFac(this));
        etudMen.addActionListener(new Manager_Ev_MenuFac(this));        
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_nomPage = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        code = new javax.swing.JLabel();
        tap_nom = new javax.swing.JTextField();
        tap_code = new javax.swing.JTextField();
        bt_enr = new javax.swing.JButton();
        bt_mod = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        nav_Men = new javax.swing.JMenu();
        inscrMen = new javax.swing.JMenuItem();
        depMen = new javax.swing.JMenuItem();
        clasMen = new javax.swing.JMenuItem();
        depClMen = new javax.swing.JMenuItem();
        etudMen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lab_nomPage.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lab_nomPage.setText("Page pour gerer les Facultes");

        nom.setText("Nom");

        code.setText("Code");

        bt_enr.setText("Enregistrer les Facultes");

        bt_mod.setText("Modifier les Facultés");
        bt_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        nav_Men.setText("Navigation_Menu");
        nav_Men.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N

        inscrMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        inscrMen.setText("Inscription");
        inscrMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrMenActionPerformed(evt);
            }
        });
        nav_Men.add(inscrMen);

        depMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        depMen.setText("Département");
        depMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depMenActionPerformed(evt);
            }
        });
        nav_Men.add(depMen);

        clasMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        clasMen.setText("Classe");
        clasMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasMenActionPerformed(evt);
            }
        });
        nav_Men.add(clasMen);

        depClMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        depClMen.setText("Département_Classe");
        depClMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depClMenActionPerformed(evt);
            }
        });
        nav_Men.add(depClMen);

        etudMen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        etudMen.setText("Etudiant");
        etudMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudMenActionPerformed(evt);
            }
        });
        nav_Men.add(etudMen);

        jMenuBar1.add(nav_Men);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_enr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom)
                            .addComponent(code))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tap_nom)
                            .addComponent(tap_code, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addComponent(lab_nomPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lab_nomPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(tap_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code)
                    .addComponent(tap_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_enr)
                    .addComponent(bt_mod))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modActionPerformed

    private void inscrMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscrMenActionPerformed

    private void depMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depMenActionPerformed

    private void clasMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasMenActionPerformed

    private void depClMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depClMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depClMenActionPerformed

    private void etudMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etudMenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaculteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaculteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaculteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaculteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaculteUI().setVisible(true);
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_enr;
    private javax.swing.JButton bt_mod;
    private javax.swing.JMenuItem clasMen;
    private javax.swing.JLabel code;
    private javax.swing.JMenuItem depClMen;
    private javax.swing.JMenuItem depMen;
    private javax.swing.JMenuItem etudMen;
    private javax.swing.JMenuItem inscrMen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lab_nomPage;
    private javax.swing.JMenu nav_Men;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField tap_code;
    private javax.swing.JTextField tap_nom;
    // End of variables declaration//GEN-END:variables

    public JTextField getTap_code() {
        return tap_code;
    }

    public JTextField getTap_nom() {
        return tap_nom;
    }

}
